import subprocess
import sys
import argparse
import os
import re
import json
from datetime import datetime

# Optional: anthropic is required for live AI reviews
try:
    import anthropic
except ImportError:
    anthropic = None

# Security patterns to scan in the diff
SECURITY_PATTERNS = {
    "Potential Secret/Token": r"(?i)(password|secret|key|token|auth|pwd)[ \t]*[:=][ \t]*['\"][^'\"]+['\"]",
    "Hardcoded AWS/API Key": r"[A-Za-z0-9/+=]{40,}",
    "Private Key": r"-----BEGIN [A-Z ]+ PRIVATE KEY-----",
    "Environment File": r"\.env(\..+)?",
    "Dangerous Permission": r"chmod\s+777",
}

def get_pr_diff(repo, pr_number):
    """Fetch the diff for a PR using gh CLI."""
    try:
        cmd = ['gh', 'pr', 'diff', str(pr_number)]
        if repo:
            cmd.extend(['--repo', repo])
        
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error fetching PR diff: {e.stderr}")
        sys.exit(1)
    except FileNotFoundError:
        print("Error: 'gh' CLI not found. Please install GitHub CLI (https://cli.github.com/).")
        sys.exit(1)

def scan_security(diff):
    """Scan the diff for potential security risks."""
    findings = []
    for name, pattern in SECURITY_PATTERNS.items():
        if re.search(pattern, diff):
            findings.append(name)
    return findings

def analyze_diff(diff, security_findings, mock=False):
    """
    Analyze the diff and return structured Markdown using Claude AI.
    """
    if mock:
        return f"""
## 🤖 Claude Code PR Review (MOCK)

### 📝 Summary of Changes
This is a mock review of the changes. The diff contains approximately {len(diff)} characters.

### 📋 Per-File Analysis
| File | Changes | Risk Level |
|------|---------|------------|
| (Mock) | Changes detected in diff | Low |

### ⚠️ Identified Risks
- **Security**: {', '.join(security_findings) if security_findings else 'No patterns detected.'}
- **Logic**: Edge cases should be verified manually.

### 📊 Confidence Score
**High** (Rule-based scan)
"""

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return "Error: ANTHROPIC_API_KEY not found in environment. Use --mock for testing without an API key."

    if not anthropic:
        return "Error: 'anthropic' package not installed. Run 'pip install anthropic'."

    client = anthropic.Anthropic(api_key=api_key)
    
    security_note = ""
    if security_findings:
        security_note = f"\n⚠️ **Automated Scan Findings:** Potential risks detected: {', '.join(security_findings)}\n"

    prompt = f"""
You are an expert Senior Software Engineer and Security Auditor.
Analyze the following PR diff and provide a comprehensive, structured Markdown review.

{security_note}

Diff:
{diff[:30000]} 

Your review MUST follow this structure:

## 🤖 Claude Code PR Review

### 📝 Summary of Changes
(Provide a high-level overview of what this PR achieves in 2-3 sentences.)

### 📋 Per-File Analysis
| File | Changes | Risk Level |
|------|---------|------------|
| file_path | summary of changes | Low/Medium/High |

### ⚠️ Identified Risks
- **Security**: (e.g., auth bypass, hardcoded secrets, injection vulnerabilities)
- **Performance**: (e.g., N+1 queries, inefficient loops)
- **Logic**: (e.g., edge cases not handled, breaking changes)

### 💡 Improvement Suggestions
- (Provide specific, actionable code improvements or refactorings)

### 📊 Confidence Score
**Low / Medium / High** (Explain why based on the complexity of the diff)

---
*Review generated by Claude PR Reviewer Agent v2*
"""
    
    try:
        message = client.messages.create(
            model="claude-3-5-sonnet-20240620",
            max_tokens=2048,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        return message.content[0].text
    except Exception as e:
        return f"Error calling Claude API: {str(e)}"

def main():
    parser = argparse.ArgumentParser(description="PR Reviewer Agent - Analyze PR diffs with Claude AI.")
    parser.add_argument("--pr", help="PR number or URL", required=True)
    parser.add_argument("--repo", help="Repository (owner/repo format)")
    parser.add_argument("--output", help="Output file path (Markdown)")
    parser.add_argument("--mock", action="store_true", help="Run in mock mode (no AI call)")
    
    args = parser.parse_args()
    
    # Handle PR URL or number
    pr_input = args.pr
    repo = args.repo
    
    if "github.com/" in pr_input:
        # Extract owner/repo and PR number from URL
        parts = pr_input.split("github.com/")[-1].split("/")
        if len(parts) >= 4 and parts[2] == "pull":
            repo = f"{parts[0]}/{parts[1]}"
            pr_id = parts[3]
        else:
            print(f"Error: Invalid PR URL format: {pr_input}")
            sys.exit(1)
    else:
        pr_id = pr_input

    print(f"🚀 Fetching diff for {repo if repo else ''} PR #{pr_id}...")
    diff = get_pr_diff(repo, pr_id)
    
    print("🔍 Scanning for security patterns...")
    security_findings = scan_security(diff)
    
    print(f"🤖 Generating {'mock ' if args.mock else ''}AI review...")
    review = analyze_diff(diff, security_findings, mock=args.mock)
    
    if args.output:
        with open(args.output, "w") as f:
            f.write(review)
        print(f"✅ Review saved to {args.output}")
    else:
        print("\n" + "="*50)
        print(review)
        print("="*50)

if __name__ == "__main__":
    main()
